// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQMnaRj8tyRer33cVdgNreKWh3uFcY41o',
    appId: '1:813600961553:web:b96fb76d35dbbf5c29adb0',
    messagingSenderId: '813600961553',
    projectId: 'manoj-28838',
    authDomain: 'manoj-28838.firebaseapp.com',
    storageBucket: 'manoj-28838.appspot.com',
    measurementId: 'G-78EPDBGZVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtMCWGc7kPo_OnAGkp_0DiE5yQeoeXte0',
    appId: '1:813600961553:android:134cdb8008fbd31729adb0',
    messagingSenderId: '813600961553',
    projectId: 'manoj-28838',
    storageBucket: 'manoj-28838.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrwtxytQZnPYwqdbPocfxztcGyJWkMFWg',
    appId: '1:813600961553:ios:622b548991ffb5bd29adb0',
    messagingSenderId: '813600961553',
    projectId: 'manoj-28838',
    storageBucket: 'manoj-28838.appspot.com',
    iosBundleId: 'com.manoj.fcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrwtxytQZnPYwqdbPocfxztcGyJWkMFWg',
    appId: '1:813600961553:ios:d555d60265e5f60d29adb0',
    messagingSenderId: '813600961553',
    projectId: 'manoj-28838',
    storageBucket: 'manoj-28838.appspot.com',
    iosBundleId: 'com.manoj.fcm.RunnerTests',
  );
}
